# button definitions for Logitech ATTACK3
FORWARD_AXIS = 1
TURN_AXIS = 0
ADJUST_AXIS = 2
BUTTON_FIRE = 0
BUTTON_SERVO = 1
BUTTON_SERVO_CENTER = 2
BUTTON_SERVO_LEFT = 3
BUTTON_SERVO_RIGHT = 4
BUTTON_STRAFE = 5
BUTTON_STAND = 10
BUTTON_RELAX = 9

